import { useSession } from 'next-auth/react'
import React, { useContext, useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { Store } from '../utils/Store';

export default function Layout({ title, children }) {

    const { status, data: session } = useSession();


    const { state, dispatch } = useContext(Store);
    const { cart } = state;
    const [cartItemsCount, setCartItemsCount] = useState(0);
    useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0));
    }, [cart.cartItems]);
return (
    <>
    <Head>
        <title>Next12-E commerce - YouTube tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head> 

    <ToastContainer position='bottom-center' limit={1} />

        <div className='flex min-h-screen flex-col justify-between'>
            <header>
                <nav className='flex h-12 px-4 items-center shadow-md justify-between'>
                    <Link href="/">
                    <h1 className='text-gray-400 text-lg'>amazona</h1>
                    </Link>
                    <div className='flex'>
                        <Link legacyBehavior href="/cart">
                <div className="p-2 cursor-pointer">
                Cart
                {cartItemsCount > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                    {cartItemsCount}
                    </span>
                )}
                </div>
                </Link>
                    
                    {status === 'loading' ? (
                        'Loading'
                        ) : session?.user ? (
                            session.user.name
                        ) : (
                        <Link href="/login">
                            <p className='p-2'>Login</p>
                        </Link>
                    )}                    
                    </div>
                </nav>
            </header>
            <main className='container m-auto mt-4 px-4'>{children}</main>
            <footer className='flex h-10 justify-center items-center shadow-inner'>
                <a target="a_blank" href='https://www.youtube.com/watch?v=_IBlyR5mRzA&list=PLdymjCOGEzWlfINbxLlgOTMFIuD4vi01n&index=16'>YouTube Tutorial here</a>
            </footer>
        </div>
    </>
)
}
