import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next12-E commerce - YouTube tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <h1 className='text-3xl font-bold'>Next12-E commerce - YouTube tutorial</h1>
    </div>
  )
}
